import type{QuizDefinition}from"@/modules/assessment/domain/assessment";
export interface StarterSection{title:string;paragraphs:string[];checklist?:string[]}export interface StarterModule{id:string;title:string;summary:string;evidence:string;outcomes:string[];sections:StarterSection[];quickCheck:QuizDefinition}
const specs=[
["va-01-work-reality","VA Work Reality","Understand remote work models, ownership, schedules, and professional boundaries.","Work-readiness checklist",["Explain common VA work arrangements","Set realistic schedule and feedback expectations","Use clear approval boundaries"],["Clients buy reliable output, not online presence.","Confirm the result, deadline, owner, and blockers.","Ask before changing money, access, or customer data."],["Ask before changing spend","Confirm output, deadline, progress, and blockers"]],
["va-02-home-work-setup","Home Work Setup","Build a usable device, connection, backup, security, and file plan.","Personal setup plan",["Test a realistic work setup","Create power and connection backups","Use secure access and file rules"],["Test calls, browser tools, and spreadsheets together.","A backup must work during your actual shift.","Use multi-factor authentication and delegated access."],["Use approved access or a password manager","Use a tested backup plan"]],
["va-03-core-digital-skills","Core Digital Skills","Practice email, calendars, cloud files, spreadsheets, tasks, and screenshots.","Tool skills assessment",["Write searchable updates","Organize files and source data","Show evidence of completed work"],["Lead emails with the result or decision needed.","Protect raw data before editing spreadsheets.","Attach links, rows, or screenshots as proof."],["Name output, scope, and next decision","Protect the only raw-data copy"]],
["va-04-clear-client-communication","Clear Client Communication","Write updates, questions, and escalations that reduce confusion.","Client update exercise",["Write concise status updates","Ask focused clarifying questions","Escalate risk without blame"],["Put the result or risk in the first two lines.","Show what you checked before asking.","State impact, containment, and the next update time."],["Share impact and recovery plan early","Ask a specific question with context"]],
["va-05-career-shift-mapping","Career Shift Mapping","Translate previous work into credible skills, evidence stories, and a focused plan.","Career shift map",["Identify transferable skills","Write evidence-based experience stories","Prioritize learning gaps"],["Transfer skills, not old job titles.","Show the situation, action, result, and lesson.","Label simulated work clearly and honestly."],["Use specific task and result evidence","Label simulated work as simulated"]],
["va-06-client-safety","Client Safety","Recognize scams and handle payments, trials, access, and confidentiality safely.","Risk scenario score",["Spot common scam signals","Set safe trial and payment rules","Use least-privilege access"],["Never move client funds through your personal account.","Agree on scope and payment before substantial work.","Pause requests that create legal or account risk."],["Refuse and verify suspicious money movement","Use only permissions needed for the task"]],
["va-07-amazon-career-map","Amazon Career Map","Understand Amazon support roles and how PPC connects to retail operations.","Specialization decision",["Describe major Amazon work areas","Explain PPC dependencies","Choose a next route using evidence"],["Listings, inventory, price, and ads affect one another.","PPC operators diagnose before changing bids.","Specialization fit comes from practice, not hype."],["Check listing, inventory, price, and structure","Review search terms and make controlled decisions"]],
["va-08-readiness-assessment","Readiness Assessment","Review setup, habits, safety, and the next learning route.","Recommended learning route",["Review practical work requirements","Identify the highest-priority gap","Choose an honest next route"],["Readiness means safe and reliable, not perfect.","Fix reliability and security before cosmetic profile work.","Training and simulated practice are not client experience."],["Fix missing backup and unsafe password storage","Describe training as training, not client work"]]
] as const;
function make(s:typeof specs[number]):StarterModule{const[id,title,summary,evidence,outcomes,paragraphs,answers]=s;const p=id.slice(3,5);return{id,title,summary,evidence,outcomes:[...outcomes],sections:[{title:"The practical standard",paragraphs:[paragraphs[0],"Use a repeatable process instead of relying on memory."]},{title:"How to apply it",paragraphs:[paragraphs[1],"Record the decision and the evidence that supports it."]},{title:"What to watch for",paragraphs:[paragraphs[2],"When risk is unclear, pause and ask a focused question."],checklist:["Confirm the goal","Protect access and data","Show evidence","Escalate blockers early"]}],quickCheck:{id:`${id}-check`,lessonId:id,version:1,passPercent:80,questions:[{id:`${p}-q1`,prompt:"Which action follows the lesson standard?",choices:[{id:"a",label:answers[0]},{id:"b",label:"Guess and explain later"},{id:"c",label:"Hide the blocker"}],correctChoiceId:"a",explanation:answers[0]},{id:`${p}-q2`,prompt:"Which practice protects trust?",choices:[{id:"a",label:"Use vague claims"},{id:"b",label:answers[1]},{id:"c",label:"Skip documentation"}],correctChoiceId:"b",explanation:answers[1]}]}}}
export const STARTER_MODULES:StarterModule[]=specs.map(make);export const getStarterModule=(id:string)=>STARTER_MODULES.find(x=>x.id===id);
