import type {Route} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {submitPpcFoundationsQuizAction} from "@/app/actions/ppc-foundations";
import {StarterQuiz} from "@/components/curriculum/StarterQuiz";
import {requireCurrentUser} from "@/lib/server/auth";
import {getPpcFoundationsService} from "@/modules/ppc-foundations/application/runtime";
import {PPC_FOUNDATIONS_MODULES,getPpcFoundationsModule} from "@/modules/ppc-foundations/domain/content";

export default async function PpcFoundationLessonPage({params}:{params:Promise<{lessonId:string}>}){
  const{lessonId}=await params,lesson=getPpcFoundationsModule(lessonId);if(!lesson)notFound();
  const user=await requireCurrentUser();const[access,progress]=await Promise.all([getPpcFoundationsService().getAccess(user.id),getPpcFoundationsService().getSummary(user.id)]);
  if(!access.allowed)return <div className="app-page lesson-page"><Link className="lesson-back" href={"/app/courses/ppc-foundations" as Route}>← Back to course</Link><section className="locked-lesson"><p className="eyebrow">ROUTE LOCKED</p><h1>{lesson.title}</h1><p>{access.reason}</p><Link className="btn btn-primary" href={"/app/courses/amazon-foundations" as Route}>Open Amazon Foundations</Link></section></div>;
  const done=new Set(progress.completedLessonIds),index=PPC_FOUNDATIONS_MODULES.findIndex(item=>item.id===lesson.id),locked=PPC_FOUNDATIONS_MODULES.slice(0,index).some(item=>!done.has(item.id)),previous=PPC_FOUNDATIONS_MODULES[index-1],next=PPC_FOUNDATIONS_MODULES[index+1];
  if(locked)return <div className="app-page lesson-page"><Link className="lesson-back" href={"/app/courses/ppc-foundations" as Route}>← Back to course</Link><section className="locked-lesson"><p className="eyebrow">MODULE LOCKED</p><h1>{lesson.title}</h1><p>Complete the previous module and pass its quick check first.</p>{previous&&<Link className="btn btn-primary" href={`/app/courses/ppc-foundations/${previous.id}` as Route}>Go to previous lesson</Link>}</section></div>;
  const quiz={lessonId:lesson.id,version:lesson.quickCheck.version,passPercent:lesson.quickCheck.passPercent,questions:lesson.quickCheck.questions.map(({id,prompt,choices})=>({id,prompt,choices}))};
  return <div className="app-page lesson-page"><Link className="lesson-back" href={"/app/courses/ppc-foundations" as Route}>← Back to course</Link><header className="lesson-hero ppc-lesson-hero"><div><p className="eyebrow light">PPC FOUNDATIONS / MODULE {String(index+1).padStart(2,"0")}</p><h1>{lesson.title}</h1><p>{lesson.summary}</p></div><aside><span className="mono">EVIDENCE</span><strong>{lesson.evidence}</strong><small>{done.has(lesson.id)?"Completed":"Pass the quick check"}</small></aside></header><div className="lesson-layout"><article className="lesson-content"><section className="lesson-outcomes"><p className="eyebrow">What you will be able to do</p><ul>{lesson.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul>{lesson.toolHref&&<Link className="btn btn-primary" href={lesson.toolHref as Route}>Open the TACoS calculator →</Link>}</section>{lesson.sections.map((section,sectionIndex)=><section key={section.title} className="lesson-section"><span className="lesson-section-number">{String(sectionIndex+1).padStart(2,"0")}</span><div><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.checklist&&<ul className="lesson-checklist">{section.checklist.map(item=><li key={item}>{item}</li>)}</ul>}</div></section>)}<StarterQuiz quiz={quiz} action={submitPpcFoundationsQuizAction} completed={done.has(lesson.id)}/><nav className="lesson-navigation">{previous?<Link href={`/app/courses/ppc-foundations/${previous.id}` as Route}>← {previous.title}</Link>:<span/>}{next&&done.has(lesson.id)?<Link href={`/app/courses/ppc-foundations/${next.id}` as Route}>{next.title} →</Link>:<Link href={"/app/courses/ppc-foundations" as Route}>Course overview →</Link>}</nav></article><aside className="lesson-progress-rail"><span className="mono">PPC FOUNDATIONS</span><strong>{progress.percentage}%</strong><p>{progress.completedLessons} of {progress.totalLessons} modules complete.</p><ol>{PPC_FOUNDATIONS_MODULES.map((item,itemIndex)=><li key={item.id} data-current={item.id===lesson.id||undefined} data-complete={done.has(item.id)||undefined}><span>{String(itemIndex+1).padStart(2,"0")}</span>{item.title}</li>)}</ol></aside></div></div>;
}
