import type {Route} from "next";
import Link from "next/link";
import {requireCurrentUser} from "@/lib/server/auth";
import {getPpcFoundationsService} from "@/modules/ppc-foundations/application/runtime";
import {PPC_FOUNDATIONS_MODULES} from "@/modules/ppc-foundations/domain/content";

export default async function PpcFoundationsPage(){
  const user=await requireCurrentUser();
  const[access,progress]=await Promise.all([getPpcFoundationsService().getAccess(user.id),getPpcFoundationsService().getSummary(user.id)]);
  if(!access.allowed)return <div className="app-page"><Link className="lesson-back" href={"/app/courses" as Route}>← Back to learning routes</Link><section className="locked-lesson"><p className="eyebrow">PPC FOUNDATIONS / LOCKED</p><h1>Understand Amazon operations first.</h1><p>{access.reason}</p><Link className="btn btn-primary" href={"/app/courses/amazon-foundations" as Route}>Open Amazon Foundations</Link></section></div>;
  const done=new Set(progress.completedLessonIds);
  return <div className="app-page"><Link className="lesson-back" href={"/app/courses" as Route}>← Back to learning routes</Link><header className="course-hero ppc-course-hero"><p className="eyebrow light">ROUTE 03 / PPC FOUNDATIONS</p><h1>Learn the controls before managing spend.</h1><p>Build metric literacy, understand SP, SB, and SD, control targeting, and make safe bid, budget, and search-term decisions.</p><div><span>{progress.totalLessons} modules</span><span>{progress.completedLessons} complete</span><span>{progress.percentage}% progress</span></div></header><section className="diagnostic-banner ppc-diagnostic"><span className="mono">OPERATING RULE</span><strong>State the evidence and the business guardrail before changing a bid, budget, negative, placement, or structure.</strong><p>Holding is a valid decision.</p></section><section className="module-list"><h2>Course modules</h2>{PPC_FOUNDATIONS_MODULES.map((lesson,index)=>{const complete=done.has(lesson.id),open=index===0||PPC_FOUNDATIONS_MODULES.slice(0,index).every(item=>done.has(item.id));return <article key={lesson.id}><span>{String(index+1).padStart(2,"0")}</span><div><small>{complete?"COMPLETED":open?"READY":"LOCKED"}</small><h3>{lesson.title}</h3><p>{lesson.summary}</p><em>{lesson.evidence}</em></div>{open?<Link className={complete?"btn btn-secondary":"btn btn-primary"} href={`/app/courses/ppc-foundations/${lesson.id}` as Route}>{complete?"Review lesson":"Open lesson"}</Link>:<b>—</b>}</article>})}</section>{progress.percentage===100&&<section className="course-complete"><p className="eyebrow">PPC FOUNDATIONS COMPLETE</p><h2>The next gate is guided campaign operation.</h2><p>Campaign Operator simulations and the full skills gate remain under development and are not represented as complete.</p></section>}</div>;
}
